### ISSUE TITLE
About self-consistent NEGF calculation

### ISSUE THREAD

**Issue by floatingCatty** [freude/NanoNet#97]
Thanks for your work in providing such a convenient and efficient algorithm of Tight Binding framework under python.

I am wondering if the method of Podolskiy and Vogl can support an updating of TB hamiltonian due to the external potential?

**Comment by freude** [comment]
I am pretty sure it can be done. The method of Podolskiy and Vogt gives only the angular dependence for the orbitals. Now the question is how smooth the external potential is at the scale of the unit cell. Is it able to affect the angular distribution of electrons at the scale of an inter-atomic distance? If you would like to work on a new feature or algorithm, let consider a specific example or problem. What do you have in mind? Is this an external potential or Hartree potential from the mean-field theory?

**Comment by freude** [comment]
An external potential can be added to the on-site potential (diagonal elements of the Hamiltonian).

**Comment by floatingCatty** [comment]
Yes, a hatree potential when conducting NEGF-poisson loop, and external potential in FET for example.

**Comment by freude** [comment]
I am working on this feature right now, I will send an update in the next couple of days. The test is going to be on the standard double barrier tunnel diode.

**Comment by floatingCatty** [comment]
That's great! Looking forward to it, thx.
